### ISSUE TITLE
[meta] + [interact]  fignoler le mode d'interaction à deux roues

### ISSUE THREAD

**Issue by gllmAR** [gllmAR/oscillographe#9]
* [x] roue arrière, peut-être speed + volume?
* [ ] roue avant, changer de preset
* [x] soft mapper osc in
